spring.application.name=MoneyManage
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}
server.port=8080
server.address=0.0.0.0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.hikari.maximum-pool-size=2
